name: ConnectivityControl CD

on:
  push:
    branches:
      - production
      - development

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter Version
        run: flutter --version

      - name: Install Dependencies
        run: flutter pub get

      - name: Analyze Code
        run: flutter analyze

      - name: Publish to pub.dev
        env:
          PUB_CREDENTIALS: ${{ secrets.PUB_CREDENTIALS }}
        run: |
          mkdir -p "$HOME/.config/dart"
          echo "$PUB_CREDENTIALS" > "$HOME/.config/dart/pub-credentials.json"
          flutter pub publish --force
