name: ConnectivityControl CD

on:
  workflow_run:
    workflows: [ "ConnectivityControl CI" ]
    types:
      - completed

jobs:
  publish:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'production'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install Deps
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Publish to pub.dev
        env:
          PUB_CREDENTIALS: ${{ secrets.PUB_CREDENTIALS }}
        run: |
          mkdir -p "$HOME/.config/dart"
          echo "$PUB_CREDENTIALS" > "$HOME/.config/dart/pub-credentials.json"
          flutter pub publish --force